package br.com.sevp.model.entity;
// Generated 18/11/2016 16:33:14 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cidades generated by hbm2java
 */
@Entity
@Table(name = "cidades", schema = "public")
public class Cidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -12686166939358820L;
	private int id;
	private Estados estados;
	private String nome;
	private Integer codigoIbge;
	private Integer populacao2010;
	private long densidadeDemo;
	private String gentilico;
	private long area;

	public Cidades() {
	}

	public Cidades(int id) {
		this.id = id;
	}

	public Cidades(int id, Estados estados, String nome, Integer codigoIbge, Integer populacao2010, long densidadeDemo,
			String gentilico, long area) {
		this.id = id;
		this.estados = estados;
		this.nome = nome;
		this.codigoIbge = codigoIbge;
		this.populacao2010 = populacao2010;
		this.densidadeDemo = densidadeDemo;
		this.gentilico = gentilico;
		this.area = area;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado_id")
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "codigo_ibge")
	public Integer getCodigoIbge() {
		return this.codigoIbge;
	}

	public void setCodigoIbge(Integer codigoIbge) {
		this.codigoIbge = codigoIbge;
	}

	@Column(name = "populacao_2010")
	public Integer getPopulacao2010() {
		return this.populacao2010;
	}

	public void setPopulacao2010(Integer populacao2010) {
		this.populacao2010 = populacao2010;
	}

	@Column(name = "densidade_demo", precision = 131089, scale = 0)
	public long getDensidadeDemo() {
		return this.densidadeDemo;
	}

	public void setDensidadeDemo(long densidadeDemo) {
		this.densidadeDemo = densidadeDemo;
	}

	@Column(name = "gentilico", length = 250)
	public String getGentilico() {
		return this.gentilico;
	}

	public void setGentilico(String gentilico) {
		this.gentilico = gentilico;
	}

	@Column(name = "area", precision = 131089, scale = 0)
	public long getArea() {
		return this.area;
	}

	public void setArea(long area) {
		this.area = area;
	}

}
