package br.com.sevp.model.entity;
// Generated 18/11/2016 16:33:14 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados", schema = "public")
public class Estados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2287601059032034852L;
	private int id;
	private String nome;
	private String sigla;
	private Set<Cidades> cidades = new HashSet<Cidades>();

	public Estados() {
	}

	public Estados(int id) {
		this.id = id;
	}

	public Estados(int id, String nome, String sigla, Set<Cidades> cidades) {
		this.id = id;
		this.nome = nome;
		this.sigla = sigla;
		this.cidades = cidades;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "sigla")
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Cidades> getCidades() {
		return this.cidades;
	}

	public void setCidadeses(Set<Cidades> cidades) {
		this.cidades = cidades;
	}

}
