package br.com.sevp.model.entity;
// Generated 28/06/2016 16:48:43 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "Pedido", schema = "dbo", catalog = "SEVP")
public class Pedido implements Serializable {

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = 8473606079397952847L;

	private long idPedido;
	private Cliente cliente;
	private Usuario usuario;
	private Date dataPedido;
	private int idSituacao;
	private String logradouro;
	private String numero;
	private String complemento;
	private String bairro;
	private String cidade;
	private String uf;
	private String cep;
	private String telefone;
	private Set<ProdutoPedido> produtoPedidos = new HashSet<ProdutoPedido>();

	public Pedido() {
	}

	public Pedido(long idPedido, Cliente cliente, Usuario usuario, Date dataPedido, int idSituacao, String logradouro,
			String numero, String bairro, String cidade, String uf, String cep, String telefone) {
		this.idPedido = idPedido;
		this.cliente = cliente;
		this.usuario = usuario;
		this.dataPedido = dataPedido;
		this.idSituacao = idSituacao;
		this.logradouro = logradouro;
		this.numero = numero;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.cep = cep;
		this.telefone = telefone;
	}

	public Pedido(long idPedido, Cliente cliente, Usuario usuario, Date dataPedido, int idSituacao, String logradouro,
			String numero, String complemento, String bairro, String cidade, String uf, String cep, String telefone,
			Set<ProdutoPedido> produtoPedidos) {
		this.idPedido = idPedido;
		this.cliente = cliente;
		this.usuario = usuario;
		this.dataPedido = dataPedido;
		this.idSituacao = idSituacao;
		this.logradouro = logradouro;
		this.numero = numero;
		this.complemento = complemento;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.cep = cep;
		this.telefone = telefone;
		this.produtoPedidos = produtoPedidos;
	}

	@Id
	@GeneratedValue
	@Column(name = "IdPedido", unique = true, nullable = false)
	public long getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(long idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdCliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	
	@Column(name = "DataPedido", nullable = false, length = 10)
	public Date getDataPedido() {
		return this.dataPedido;
	}

	public void setDataPedido(Date dataPedido) {
		this.dataPedido = dataPedido;
	}

	@Column(name = "IdSituacao", nullable = false)
	public int getIdSituacao() {
		return this.idSituacao;
	}

	public void setIdSituacao(int idSituacao) {
		this.idSituacao = idSituacao;
	}

	@Column(name = "Logradouro", nullable = false)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "Numero", nullable = false)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "Complemento")
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "Bairro", nullable = false)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "Cidade", nullable = false)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "UF", nullable = false)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "CEP", nullable = false)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "Telefone", nullable = false)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Override
	public String toString() {
		return "Pedido [idPedido=" + idPedido + ", dataPedido=" + dataPedido + ", idSituacao=" + idSituacao
				+ ", logradouro=" + logradouro + ", numero=" + numero + ", complemento=" + complemento + ", bairro="
				+ bairro + ", cidade=" + cidade + ", uf=" + uf + ", cep=" + cep + ", telefone=" + telefone + "]";
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPedido")
	public Set<ProdutoPedido> getProdutoPedidos() {
		return this.produtoPedidos;
	}

	public void setProdutoPedidos(Set<ProdutoPedido> produtoPedidos) {
		this.produtoPedidos = produtoPedidos;
	}

	

}
