package br.com.sevp.model.entity;
// Generated 28/06/2016 16:48:43 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "Produto", schema = "dbo", catalog = "SEVP")
public class Produto implements Serializable {

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = -4233974455077626577L;

	private long idProduto;
	private TipoProduto tipoProduto;
	private String nomeProduto;
	private String descricaoProduto;
	private long valorUnitario;
	private long custoUnitario;
	private Set<ProdutoPedido> produtoPedidos = new HashSet<ProdutoPedido>();

	public Produto() {
	}

	public Produto(long idProduto, TipoProduto tipoProduto, String nomeProduto, String descricaoProduto,
			long valorUnitario, long custoUnitario) {
		this.idProduto = idProduto;
		this.tipoProduto = tipoProduto;
		this.nomeProduto = nomeProduto;
		this.descricaoProduto = descricaoProduto;
		this.valorUnitario = valorUnitario;
		this.custoUnitario = custoUnitario;
	}

	public Produto(long idProduto, TipoProduto tipoProduto, String nomeProduto, String descricaoProduto,
			long valorUnitario, long custoUnitario, Set<ProdutoPedido> produtoPedidos) {
		this.idProduto = idProduto;
		this.tipoProduto = tipoProduto;
		this.nomeProduto = nomeProduto;
		this.descricaoProduto = descricaoProduto;
		this.valorUnitario = valorUnitario;
		this.custoUnitario = custoUnitario;
		this.produtoPedidos = produtoPedidos;
	}

	@Id
	@GeneratedValue
	@Column(name = "IdProduto", unique = true, nullable = false)
	public long getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(long idProduto) {
		this.idProduto = idProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTipoProduto", nullable = false)
	public TipoProduto getTipoProduto() {
		return this.tipoProduto;
	}

	public void setTipoProduto(TipoProduto tipoProduto) {
		this.tipoProduto = tipoProduto;
	}

	@Column(name = "NomeProduto", nullable = false)
	public String getNomeProduto() {
		return this.nomeProduto;
	}

	public void setNomeProduto(String nomeProduto) {
		this.nomeProduto = nomeProduto;
	}

	@Column(name = "DescricaoProduto", nullable = false)
	public String getDescricaoProduto() {
		return this.descricaoProduto;
	}

	public void setDescricaoProduto(String descricaoProduto) {
		this.descricaoProduto = descricaoProduto;
	}

	@Column(name = "ValorUnitario", nullable = false, precision = 18)
	public long getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(long valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@Column(name = "CustoUnitario", nullable = false, precision = 18)
	public long getCustoUnitario() {
		return this.custoUnitario;
	}

	public void setCustoUnitario(long custoUnitario) {
		this.custoUnitario = custoUnitario;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdProduto")
	public Set<ProdutoPedido> getProdutoPedidos() {
		return this.produtoPedidos;
	}

	public void setProdutoPedidos(Set<ProdutoPedido> produtoPedidos) {
		this.produtoPedidos = produtoPedidos;
	}

	@Override
	public String toString() {
		return "Produto [idProduto=" + idProduto + ", nomeProduto=" + nomeProduto + ", descricaoProduto="
				+ descricaoProduto + ", valorUnitario=" + valorUnitario + ", custoUnitario=" + custoUnitario + "]";
	}
}
