package br.com.sevp.model.entity;
// Generated 28/06/2016 16:48:43 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoPedido generated by hbm2java
 */
@Entity
@Table(name = "ProdutoPedido", schema = "dbo", catalog = "SEVP")
public class ProdutoPedido implements Serializable {

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = -8015591082052759278L;

	private long idProdutoPedido;
	private Pedido pedido;
	private Produto produto;
	private Integer quantidade;
	private long valorUnitario;

	public ProdutoPedido() {
	}

	public ProdutoPedido(long idProdutoPedido, Pedido pedido, Produto produto, long valorUnitario) {
		this.idProdutoPedido = idProdutoPedido;
		this.pedido = pedido;
		this.produto = produto;
		this.valorUnitario = valorUnitario;
	}

	public ProdutoPedido(long idProdutoPedido, Pedido pedido, Produto produto, Integer quantidade,
			long valorUnitario) {
		this.idProdutoPedido = idProdutoPedido;
		this.pedido = pedido;
		this.produto = produto;
		this.quantidade = quantidade;
		this.valorUnitario = valorUnitario;
	}

	@Id

	@Column(name = "IdProdutoPedido", unique = true, nullable = false)
	public long getIdProdutoPedido() {
		return this.idProdutoPedido;
	}

	public void setIdProdutoPedido(long idProdutoPedido) {
		this.idProdutoPedido = idProdutoPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdProduto", nullable = false)
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "Quantidade")
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "ValorUnitario", nullable = false, precision = 18)
	public long getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(long valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@Override
	public String toString() {
		return "ProdutoPedido [idProdutoPedido=" + idProdutoPedido + ", quantidade=" + quantidade + ", valorUnitario="
				+ valorUnitario + "]";
	}
	
	
}
