package br.com.sevp.model.entity;
// Generated 28/06/2016 16:48:43 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoProduto generated by hbm2java
 */
@Entity
@Table(name = "TipoProduto", schema = "dbo", catalog = "SEVP")
public class TipoProduto implements Serializable {

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = -953945667094487433L;

	private long idTipoProduto;
	private String descricaoTipoProduto;
	private Set<Produto> produtos = new HashSet<Produto>();

	public TipoProduto() {
	}

	public TipoProduto(long idTipoProduto, String descricaoTipoProduto) {
		this.idTipoProduto = idTipoProduto;
		this.descricaoTipoProduto = descricaoTipoProduto;
	}

	public TipoProduto(long idTipoProduto, String descricaoTipoProduto, Set<Produto> produtos) {
		this.idTipoProduto = idTipoProduto;
		this.descricaoTipoProduto = descricaoTipoProduto;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue
	@Column(name = "IdTipoProduto", unique = true, nullable = false)
	public long getIdTipoProduto() {
		return this.idTipoProduto;
	}

	public void setIdTipoProduto(long idTipoProduto) {
		this.idTipoProduto = idTipoProduto;
	}

	@Column(name = "DescricaoTipoProduto", nullable = false)
	public String getDescricaoTipoProduto() {
		return this.descricaoTipoProduto;
	}

	public void setDescricaoTipoProduto(String descricaoTipoProduto) {
		this.descricaoTipoProduto = descricaoTipoProduto;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdTipoProduto")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

	@Override
	public String toString() {
		return "TipoProduto [idTipoProduto=" + idTipoProduto + ", descricaoTipoProduto=" + descricaoTipoProduto
				+ ", produtos=" + produtos + "]";
	}

}
