package br.com.sevp.model.entity;
// Generated 07/11/2016 09:43:25 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarioroles generated by hbm2java
 */
@Entity
@Table(name = "UsuarioRoles", schema = "public")
public class UsuarioRoles implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 5255073273912356166L;

	@Id
	private String usuario;
	private String role;

	public UsuarioRoles() {
	}

	public UsuarioRoles(String usuario, String role) {
		this.usuario = usuario;
		this.role = role;
	}

	@Column(name = "usuario", nullable = false, length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "role", nullable = false, length = 15)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public String toString() {
		return "Usuarioroles [usuario=" + usuario + ", role=" + role + "]";
	}

}
